### ISSUE TITLE
把点歌指令改掉

### ISSUE THREAD

**Issue by martin-cao** [HolgerHuo/telegram-netease-bot#1]
不改给你寄刀片

**Comment by martin-cao** [comment]
![c0d8bae32a8334c35339286ee82c0b88](https://user-images.githubusercontent.com/54637858/160278943-bf0bee7a-f3de-4a9a-ba54-de2373076fc4.png)

**Comment by martin-cao** [comment]
だめ！！！

**Comment by martin-cao** [comment]
閉鎖だめ！！！

**Comment by HolgerHuo** [comment]
https://github.com/HolgerHuo/telegram-netease-bot/commit/04eaf35732d7f31cbf1aca3981c0a9f89b8a1ed0
