### ISSUE TITLE
bot搜索出现问题

### ISSUE THREAD

**Issue by Respawn-ID** [HolgerHuo/telegram-netease-bot#2]
![Screenshot_20230128_034956_org telegram messenger](https://user-images.githubusercontent.com/30469542/215184119-2cd34e63-334d-4e41-a874-09c0ff700822.jpg)
其在使用时候出现网易云歌曲搜索不到的情况
yt功能正常可使用

**Comment by HolgerHuo** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1688
This issue is caused by an upstream error.
I will be looking into this maybe later this day. 
Thanks for your feedback.

**Comment by HolgerHuo** [comment]
This problem has been resolved.
It seems that Netease has temporarily blocked our API access.
